/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RepliesRouteImport } from './routes/replies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InquiriesRouteImport } from './routes/inquiries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as SellNewRouteImport } from './routes/sell.new'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ListSlugRouteImport } from './routes/list.$slug'
import { Route as InquiriesProductIdRouteImport } from './routes/inquiries.$productId'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as ProductsIdEditRouteImport } from './routes/products.$id.edit'
import { Route as ProductsIdBuyRouteImport } from './routes/products.$id.buy'
import { Route as OrdersIdPayRouteImport } from './routes/orders.$id.pay'
import { Route as ChatProductIdBuyerIdRouteImport } from './routes/chat.$productId.$buyerId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RepliesRoute = RepliesRouteImport.update({
  id: '/replies',
  path: '/replies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesRoute = InquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellNewRoute = SellNewRouteImport.update({
  id: '/sell/new',
  path: '/sell/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListSlugRoute = ListSlugRouteImport.update({
  id: '/list/$slug',
  path: '/list/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesProductIdRoute = InquiriesProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => InquiriesRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdEditRoute = ProductsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProductsIdRoute,
} as any)
const ProductsIdBuyRoute = ProductsIdBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => ProductsIdRoute,
} as any)
const OrdersIdPayRoute = OrdersIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => OrdersIdRoute,
} as any)
const ChatProductIdBuyerIdRoute = ChatProductIdBuyerIdRouteImport.update({
  id: '/chat/$productId/$buyerId',
  path: '/chat/$productId/$buyerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRouteWithChildren
  '/login': typeof LoginRoute
  '/replies': typeof RepliesRoute
  '/signup': typeof SignupRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/inquiries/$productId': typeof InquiriesProductIdRoute
  '/list/$slug': typeof ListSlugRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/sell/new': typeof SellNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/chat/$productId/$buyerId': typeof ChatProductIdBuyerIdRoute
  '/orders/$id/pay': typeof OrdersIdPayRoute
  '/products/$id/buy': typeof ProductsIdBuyRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRouteWithChildren
  '/login': typeof LoginRoute
  '/replies': typeof RepliesRoute
  '/signup': typeof SignupRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/inquiries/$productId': typeof InquiriesProductIdRoute
  '/list/$slug': typeof ListSlugRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/sell/new': typeof SellNewRoute
  '/orders': typeof OrdersIndexRoute
  '/chat/$productId/$buyerId': typeof ChatProductIdBuyerIdRoute
  '/orders/$id/pay': typeof OrdersIdPayRoute
  '/products/$id/buy': typeof ProductsIdBuyRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inquiries': typeof InquiriesRouteWithChildren
  '/login': typeof LoginRoute
  '/replies': typeof RepliesRoute
  '/signup': typeof SignupRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/inquiries/$productId': typeof InquiriesProductIdRoute
  '/list/$slug': typeof ListSlugRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/products/$id': typeof ProductsIdRouteWithChildren
  '/sell/new': typeof SellNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/chat/$productId/$buyerId': typeof ChatProductIdBuyerIdRoute
  '/orders/$id/pay': typeof OrdersIdPayRoute
  '/products/$id/buy': typeof ProductsIdBuyRoute
  '/products/$id/edit': typeof ProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inquiries'
    | '/login'
    | '/replies'
    | '/signup'
    | '/admin/orders'
    | '/category/$slug'
    | '/inquiries/$productId'
    | '/list/$slug'
    | '/orders/$id'
    | '/products/$id'
    | '/sell/new'
    | '/orders/'
    | '/chat/$productId/$buyerId'
    | '/orders/$id/pay'
    | '/products/$id/buy'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inquiries'
    | '/login'
    | '/replies'
    | '/signup'
    | '/admin/orders'
    | '/category/$slug'
    | '/inquiries/$productId'
    | '/list/$slug'
    | '/orders/$id'
    | '/products/$id'
    | '/sell/new'
    | '/orders'
    | '/chat/$productId/$buyerId'
    | '/orders/$id/pay'
    | '/products/$id/buy'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/inquiries'
    | '/login'
    | '/replies'
    | '/signup'
    | '/admin/orders'
    | '/category/$slug'
    | '/inquiries/$productId'
    | '/list/$slug'
    | '/orders/$id'
    | '/products/$id'
    | '/sell/new'
    | '/orders/'
    | '/chat/$productId/$buyerId'
    | '/orders/$id/pay'
    | '/products/$id/buy'
    | '/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InquiriesRoute: typeof InquiriesRouteWithChildren
  LoginRoute: typeof LoginRoute
  RepliesRoute: typeof RepliesRoute
  SignupRoute: typeof SignupRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ListSlugRoute: typeof ListSlugRoute
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
  ProductsIdRoute: typeof ProductsIdRouteWithChildren
  SellNewRoute: typeof SellNewRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ChatProductIdBuyerIdRoute: typeof ChatProductIdBuyerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replies': {
      id: '/replies'
      path: '/replies'
      fullPath: '/replies'
      preLoaderRoute: typeof RepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries': {
      id: '/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof InquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/new': {
      id: '/sell/new'
      path: '/sell/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof SellNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$slug': {
      id: '/list/$slug'
      path: '/list/$slug'
      fullPath: '/list/$slug'
      preLoaderRoute: typeof ListSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/$productId': {
      id: '/inquiries/$productId'
      path: '/$productId'
      fullPath: '/inquiries/$productId'
      preLoaderRoute: typeof InquiriesProductIdRouteImport
      parentRoute: typeof InquiriesRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id/edit': {
      id: '/products/$id/edit'
      path: '/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof ProductsIdEditRouteImport
      parentRoute: typeof ProductsIdRoute
    }
    '/products/$id/buy': {
      id: '/products/$id/buy'
      path: '/buy'
      fullPath: '/products/$id/buy'
      preLoaderRoute: typeof ProductsIdBuyRouteImport
      parentRoute: typeof ProductsIdRoute
    }
    '/orders/$id/pay': {
      id: '/orders/$id/pay'
      path: '/pay'
      fullPath: '/orders/$id/pay'
      preLoaderRoute: typeof OrdersIdPayRouteImport
      parentRoute: typeof OrdersIdRoute
    }
    '/chat/$productId/$buyerId': {
      id: '/chat/$productId/$buyerId'
      path: '/chat/$productId/$buyerId'
      fullPath: '/chat/$productId/$buyerId'
      preLoaderRoute: typeof ChatProductIdBuyerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InquiriesRouteChildren {
  InquiriesProductIdRoute: typeof InquiriesProductIdRoute
}

const InquiriesRouteChildren: InquiriesRouteChildren = {
  InquiriesProductIdRoute: InquiriesProductIdRoute,
}

const InquiriesRouteWithChildren = InquiriesRoute._addFileChildren(
  InquiriesRouteChildren,
)

interface OrdersIdRouteChildren {
  OrdersIdPayRoute: typeof OrdersIdPayRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdPayRoute: OrdersIdPayRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

interface ProductsIdRouteChildren {
  ProductsIdBuyRoute: typeof ProductsIdBuyRoute
  ProductsIdEditRoute: typeof ProductsIdEditRoute
}

const ProductsIdRouteChildren: ProductsIdRouteChildren = {
  ProductsIdBuyRoute: ProductsIdBuyRoute,
  ProductsIdEditRoute: ProductsIdEditRoute,
}

const ProductsIdRouteWithChildren = ProductsIdRoute._addFileChildren(
  ProductsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InquiriesRoute: InquiriesRouteWithChildren,
  LoginRoute: LoginRoute,
  RepliesRoute: RepliesRoute,
  SignupRoute: SignupRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  CategorySlugRoute: CategorySlugRoute,
  ListSlugRoute: ListSlugRoute,
  OrdersIdRoute: OrdersIdRouteWithChildren,
  ProductsIdRoute: ProductsIdRouteWithChildren,
  SellNewRoute: SellNewRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ChatProductIdBuyerIdRoute: ChatProductIdBuyerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
